services:
  lab-pogorelov:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: node server.js
    container_name: lab-pogorelov